name: PR check naming

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: PR Lint GitHub Action
        uses: seferov/pr-lint-action@v1.2.0
        with:
          title-regex: '^TAU-\d+\s.+'
          error-message: 'Add ticket ID to your title e.g. "TAU-123"'
